# Site settings
title: FF14 Links and Stuff
email: ff14@uberfuzzy.com
description: A simple link hub and utility host
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ff14.uberfuzzy.com" # the base hostname & protocol for your site
twitter_username: uberfuzzy
github_username:  uberfuzzy

# Build settings
markdown: kramdown
exclude:
  - README.md
  - LICENSE
  - CNAME
  - .jekyll-metadata
  
collections_dir: collections
collections:
  links:
    output: false
